### ISSUE TITLE
请问怎么部署到vercel呢？

### ISSUE THREAD

**Issue by chenryace** [XRSec/wxweb#2]

**Comment by Ran-Xing** [comment]
## Build & Development Settings

### Build Command

```bash
git clone https://github.com/doocs/md.git /tmp/www && cp -r  /tmp/www/* . && npm i && npm run build:h5-netlify
```

### Output Directory

```
dist
```

**Comment by Ran-Xing** [comment]
#/doocs/md/issues/154

**Comment by chenryace** [comment]
> ## Build & Development Settings
> ### Build Command
> ```shell
> git clone https://github.com/doocs/md.git /tmp/www && cp -r  /tmp/www/* . && npm i && npm run build:h5-netlify
> ```
> 
> ### Output Directory
> ```
> dist
> ```

貌似报错了，哈哈，无所谓了，部署在本地也不错，非常感谢
